"use client";

import React, { createContext, useContext, useEffect, useState } from "react";
import { GlobeIcon, CheckIcon } from "./Icons";

export type LanguageCode = "id" | "en" | "ja" | "jv" | "su" | "zh" | "ar" | "fr";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  badge: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "id", name: "Indonesia", nativeName: "Bahasa Indonesia", flag: "🇮🇩", badge: "ID" },
  { code: "en", name: "Inggris", nativeName: "English", flag: "🇬🇧", badge: "EN" },
  { code: "ja", name: "Jepang", nativeName: "日本語", flag: "🇯🇵", badge: "JA" },
  { code: "jv", name: "Jawa", nativeName: "Basa Jawa", flag: "🇮🇩", badge: "JV" },
  { code: "su", name: "Sunda", nativeName: "Basa Sunda", flag: "🇮🇩", badge: "SU" },
  { code: "zh", name: "China", nativeName: "中文", flag: "🇨🇳", badge: "ZH" },
  { code: "ar", name: "Arab", nativeName: "العربية", flag: "🇸🇦", badge: "AR" },
  { code: "fr", name: "Prancis", nativeName: "Français", flag: "🇫🇷", badge: "FR" },
];

export const translations = {
  id: {
    nav: {
      home: "Home",
      about: "Tentang",
      skills: "Keahlian",
      contact: "Kontak",
      support: "Dukung",
      linktree: "Linktree",
    },
    hero: {
      prefix1: "Hai, Saya",
      text1: "Muhammad Dafa Pratama",
      prefix2: "Tanggal Lahir",
      text2: "28 Agustus 2009",
      tagline: "Siswa SMK Swasta Kelas XI jurusan AKL yang fokus pada bidang administrasi, pengelolaan media sosial, dan teknologi digital.",
      btnContact: "Kirim Pesan",
      btnWa: "WhatsApp",
      btnBio: "Bio / Linktree",
      statusVal: "ONLINE",
      statusLabel: "Status",
      classVal: "XI AKL",
      classLabel: "Kelas",
      schoolVal: "SMK",
      schoolLabel: "Sekolah",
      badgeSchool: "SMK · XI AKL",
    },
    countdown: {
      title: "Hitung Mundur Ulang Tahun",
      targetPrefix: "28 Agustus ·",
      days: "Hari",
      hours: "Jam",
      mins: "Menit",
      secs: "Detik",
    },
    about: {
      badge: "02. Tentang",
      titlePre: "Tentang",
      titlePost: "Aku",
      fileName: "profil.json",
      keyName: "nama",
      keySchool: "sekolah",
      valSchool: "SMK Swasta",
      keyGrade: "kelas",
      valGrade: "XI (11)",
      keyMajor: "jurusan",
      valMajor: "Akuntansi dan Keuangan Lembaga (AKL)",
      keyStatus: "status",
      valStatus: "Pelajar Aktif",
      keyInterest: "minat",
      valInterest1: "Administrasi Keuangan",
      valInterest2: "Manajemen Media Sosial",
      valInterest3: "Teknologi Digital",
      tile1Title: "Pelajar SMK Swasta",
      tile1Desc: "Menempuh pendidikan di SMK Swasta Kelas XI jurusan Akuntansi Keuangan dan Lembaga (AKL).",
      tile2Title: "Keahlian AKL",
      tile2Desc: "Menguasai dasar pembukuan, administrasi transaksi, Microsoft Excel, dan Microsoft Word.",
      tile3Title: "Digital & Social Media",
      tile3Desc: "Aktif mengelola media sosial, konten komunitas digital, dan interaksi online.",
      socialTitle: "Akun Sosial Media & Komunitas",
    },
    skills: {
      badge: "03. Keahlian",
      titlePre: "Keahlian",
      titlePost: "Ku",
      skillExcel: "Microsoft Excel",
      skillWord: "Microsoft Word",
      skillSocial: "Social Media Mgmt",
      waTitle: "Komunitas & Saluran WhatsApp",
      waDesc: "Grup diskusi dan update seputar aktivitas Dafa",
      joinGroup: "Gabung Grup WA",
      followChannel: "Ikuti Saluran WA",
    },
    contact: {
      badge: "04. Kontak",
      titlePre: "Hubungi",
      titlePost: "Aku",
      desc: "Ada pertanyaan atau ingin kolaborasi? Kirim pesan langsung ke bot Telegram ku!",
      formBar: "FORM_PESAN.SYS",
      labelName: "Nama Lengkap / Panggilan:",
      phName: "Masukkan nama kamu...",
      labelContact: "Kontak Balasan (No. WA / Username Telegram):",
      phContact: "Contoh: 08123456789 atau @username",
      labelMsg: "Pesan:",
      phMsg: "Tulis pesan atau keperluan kamu...",
      sliderIdle: "Geser ke kanan untuk verifikasi",
      sliderFailed: "! Geser sampai ujung kanan",
      sliderVerified: "✓ Terverifikasi!",
      sliderHint: "Geser ke kanan →",
      readyToSend: "Terverifikasi — Siap Dikirim!",
      btnSend: "Kirim Pesan Sekarang →",
      btnSending: "Mengirim Pesan...",
      successTitle: "Pesan Berhasil Terkirim!",
      successDesc: "Notifikasi sudah langsung masuk ke Telegram ku. Aku akan respon ke kontak yang kamu berikan.",
      btnSendAnother: "Kirim Pesan Lain",
    },
    payment: {
      badge: "05. Support & Donasi",
      titlePre: "Dukung",
      titlePost: "Aku",
      desc: "Dukungan atau donasi dapat disalurkan melalui nomor e-wallet atau scan QRIS di bawah:",
      copyBtn: "Salin",
      copiedBtn: "Disalin",
      saweriaTitle: "Saweria Tip & Donasi",
      saweriaOpen: "Buka →",
      qrisTitle: "Scan Pembayaran QRIS",
      qrisSub: "Klik untuk membuka QRIS fullscreen",
      qrisBtn: "Lihat QRIS Fullscreen",
      modalClose: "Tutup",
      modalBadge: "QRIS PAYMENT",
      modalInfo: "Muhammad Dafa Pratama · Dana / Gopay / OVO / ShopeePay / Bank",
      modalDownload: "Download Gambar QRIS",
    },
    footer: {
      builtBy: "Dibuat oleh",
      linktree: "Halaman Linktree",
      sub: "SMK XI AKL · Indonesia",
    },
    linksPage: {
      backHome: "Website Portfolio",
      shareTooltip: "Bagikan Halaman Ini",
      copiedToast: "Tersalin ke clipboard!",
      profileDesc: "Siswa SMK Swasta Kelas XI AKL · Digital Creator & Content Creator",
      btnWebsite: "Kunjungi Website Utama Portfolio →",
      catWa: "WhatsApp & Komunitas",
      catSocial: "Media Sosial Resmi",
      catSupport: "Dukungan & Donasi",
      waPersonal: "WhatsApp Chat Pribadi",
      waPersonalSub: "Kirim pesan / ngobrol langsung",
      waGroup: "WhatsApp Group Komunitas",
      waGroupSub: "Gabung ke grup diskusi & silaturahmi",
      waChannel: "WhatsApp Saluran Resmi",
      waChannelSub: "Info update & pengumuman terbaru",
      saweriaSub: "Donasi & apresiasi via Saweria",
      qrisBtnText: "Tampilkan QRIS Pembayaran",
      qrisSubText: "Scan via Dana, Gopay, OVO, ShopeePay & M-Banking",
    },
  },
  en: {
    nav: {
      home: "Home",
      about: "About",
      skills: "Skills",
      contact: "Contact",
      support: "Support",
      linktree: "Linktree",
    },
    hero: {
      prefix1: "Hi, I'm",
      text1: "Muhammad Dafa Pratama",
      prefix2: "Date of Birth",
      text2: "August 28, 2009",
      tagline: "11th Grade Private Vocational High School student majoring in Accounting, focused on office administration, social media, and digital tech.",
      btnContact: "Send Message",
      btnWa: "WhatsApp",
      btnBio: "Bio / Linktree",
      statusVal: "ONLINE",
      statusLabel: "Status",
      classVal: "11th AKL",
      classLabel: "Grade",
      schoolVal: "SMK",
      schoolLabel: "School",
      badgeSchool: "SMK · 11th AKL",
    },
    countdown: {
      title: "Birthday Countdown",
      targetPrefix: "August 28 ·",
      days: "Days",
      hours: "Hours",
      mins: "Minutes",
      secs: "Seconds",
    },
    about: {
      badge: "02. About",
      titlePre: "About",
      titlePost: "Me",
      fileName: "profile.json",
      keyName: "name",
      keySchool: "school",
      valSchool: "Private Vocational High",
      keyGrade: "grade",
      valGrade: "11th Grade",
      keyMajor: "major",
      valMajor: "Accounting & Institutional Finance (AKL)",
      keyStatus: "status",
      valStatus: "Active Student",
      keyInterest: "interests",
      valInterest1: "Financial Administration",
      valInterest2: "Social Media Management",
      valInterest3: "Digital Technology",
      tile1Title: "Vocational Student",
      tile1Desc: "Enrolled in 11th Grade Vocational School majoring in Accounting and Institutional Finance.",
      tile2Title: "Accounting Skills",
      tile2Desc: "Proficient in basic bookkeeping, transaction administration, Microsoft Excel, and Word.",
      tile3Title: "Digital & Social Media",
      tile3Desc: "Actively managing digital communities, online content creation, and social platforms.",
      socialTitle: "Social Media & Community Accounts",
    },
    skills: {
      badge: "03. Skills",
      titlePre: "My",
      titlePost: "Skills",
      skillExcel: "Microsoft Excel",
      skillWord: "Microsoft Word",
      skillSocial: "Social Media Mgmt",
      waTitle: "WhatsApp Community & Channel",
      waDesc: "Discussion group & daily updates around Dafa's activities",
      joinGroup: "Join WA Group",
      followChannel: "Follow WA Channel",
    },
    contact: {
      badge: "04. Contact",
      titlePre: "Contact",
      titlePost: "Me",
      desc: "Have a question or want to collaborate? Send a message directly to my Telegram bot!",
      formBar: "MESSAGE_FORM.SYS",
      labelName: "Full Name / Nickname:",
      phName: "Enter your name...",
      labelContact: "Reply Contact (WhatsApp / Telegram):",
      phContact: "e.g. +62812345678 or @username",
      labelMsg: "Message:",
      phMsg: "Write your message or inquiry here...",
      sliderIdle: "Slide right to verify",
      sliderFailed: "! Slide all the way to the right",
      sliderVerified: "✓ Verified!",
      sliderHint: "Slide to right →",
      readyToSend: "Verified — Ready to Send!",
      btnSend: "Send Message Now →",
      btnSending: "Sending Message...",
      successTitle: "Message Sent Successfully!",
      successDesc: "Your notification arrived at my Telegram bot. I will get back to you promptly!",
      btnSendAnother: "Send Another Message",
    },
    payment: {
      badge: "05. Support & Donate",
      titlePre: "Support",
      titlePost: "Me",
      desc: "Any appreciation or support can be sent via e-wallet numbers or by scanning QRIS below:",
      copyBtn: "Copy",
      copiedBtn: "Copied",
      saweriaTitle: "Saweria Tip & Donation",
      saweriaOpen: "Open →",
      qrisTitle: "Scan QRIS Payment",
      qrisSub: "Click to view QRIS fullscreen",
      qrisBtn: "View QRIS Fullscreen",
      modalClose: "Close",
      modalBadge: "QRIS PAYMENT",
      modalInfo: "Muhammad Dafa Pratama · Dana / Gopay / OVO / ShopeePay / Bank",
      modalDownload: "Download QRIS Image",
    },
    footer: {
      builtBy: "Built by",
      linktree: "Linktree Page",
      sub: "SMK 11th AKL · Indonesia",
    },
    linksPage: {
      backHome: "Portfolio Website",
      shareTooltip: "Share This Page",
      copiedToast: "Copied to clipboard!",
      profileDesc: "11th Grade Vocational Student · Digital & Content Creator",
      btnWebsite: "Visit Main Portfolio Website →",
      catWa: "WhatsApp & Community",
      catSocial: "Official Social Media",
      catSupport: "Support & Donation",
      waPersonal: "Personal WhatsApp Chat",
      waPersonalSub: "Send direct message / chat",
      waGroup: "WhatsApp Community Group",
      waGroupSub: "Join discussion & networking group",
      waChannel: "Official WhatsApp Channel",
      waChannelSub: "Latest announcements & updates",
      saweriaSub: "Tip & support via Saweria",
      qrisBtnText: "Show QRIS Payment",
      qrisSubText: "Scan via Dana, Gopay, OVO, ShopeePay & M-Banking",
    },
  },
  ja: {
    nav: {
      home: "ホーム",
      about: "自己紹介",
      skills: "スキル",
      contact: "連絡先",
      support: "応援",
      linktree: "リンク集",
    },
    hero: {
      prefix1: "こんにちは、私は",
      text1: "ムハンマド・ダファ・プラタマ",
      prefix2: "生年月日",
      text2: "2009年8月28日",
      tagline: "私立職業高校2年生（会計科）。事務管理、SNS運営、デジタル技術に注力しています。",
      btnContact: "メッセージを送る",
      btnWa: "WhatsApp",
      btnBio: "リンク集 / バイオ",
      statusVal: "オンライン",
      statusLabel: "ステータス",
      classVal: "高校2年 会計科",
      classLabel: "学年",
      schoolVal: "職業高校",
      schoolLabel: "学校",
      badgeSchool: "職業高校 · 会計科",
    },
    countdown: {
      title: "誕生日カウントダウン",
      targetPrefix: "8月28日 ·",
      days: "日",
      hours: "時間",
      mins: "分",
      secs: "秒",
    },
    about: {
      badge: "02. 自己紹介",
      titlePre: "私に",
      titlePost: "ついて",
      fileName: "profile.json",
      keyName: "氏名",
      keySchool: "学校",
      valSchool: "私立職業高校",
      keyGrade: "学年",
      valGrade: "高校2年生 (11期)",
      keyMajor: "専攻",
      valMajor: "会計・機関財務専攻 (AKL)",
      keyStatus: "ステータス",
      valStatus: "在学中",
      keyInterest: "興味分野",
      valInterest1: "財務事務管理",
      valInterest2: "SNSコミュニティ運営",
      valInterest3: "デジタル技術",
      tile1Title: "私立高校生",
      tile1Desc: "会計および機関財務科（AKL）の高校2年生として勉学に励んでいます。",
      tile2Title: "会計スキル",
      tile2Desc: "基本的な簿記、取引事務、Microsoft Excel、Wordを習熟。",
      tile3Title: "デジタル＆SNS",
      tile3Desc: "SNSコンテンツ制作やコミュニティ運営に積極的に取り組んでいます。",
      socialTitle: "公式SNS＆コミュニティ",
    },
    skills: {
      badge: "03. スキル",
      titlePre: "私の",
      titlePost: "特技",
      skillExcel: "マイクロソフト Excel",
      skillWord: "マイクロソフト Word",
      skillSocial: "SNSマーケティング",
      waTitle: "WhatsApp公式コミュニティ",
      waDesc: "ダファの活動に関する最新情報や交流グループ",
      joinGroup: "グループに参加",
      followChannel: "公式チャンネル登録",
    },
    contact: {
      badge: "04. 連絡先",
      titlePre: "連絡",
      titlePost: "する",
      desc: "ご質問やコラボのお誘いはTelegram botへ直接メッセージをお送りください！",
      formBar: "MESSAGE_BOX.SYS",
      labelName: "お名前 / ニックネーム:",
      phName: "お名前を入力...",
      labelContact: "返信先連絡先（WA番号 / Telegram）:",
      phContact: "例: 0812345678 または @username",
      labelMsg: "メッセージ内容:",
      phMsg: "メッセージをご記入ください...",
      sliderIdle: "右にスライドして認証",
      sliderFailed: "! 端までしっかりスライドしてください",
      sliderVerified: "✓ 認証完了！",
      sliderHint: "右へスライド →",
      readyToSend: "認証済み — 送信準備完了！",
      btnSend: "メッセージを送信する →",
      btnSending: "送信中...",
      successTitle: "送信が完了しました！",
      successDesc: "Telegram botへ届きました。記載の連絡先へ折り返し返信いたします。",
      btnSendAnother: "別のメッセージを送る",
    },
    payment: {
      badge: "05. 応援・ドネーション",
      titlePre: "活動を",
      titlePost: "応援",
      desc: "活動支援やドネーションは電子マネーまたはQRISコードをご利用いただけます：",
      copyBtn: "コピー",
      copiedBtn: "完了",
      saweriaTitle: "Saweria ドネーション",
      saweriaOpen: "開く →",
      qrisTitle: "QRIS決済コード",
      qrisSub: "クリックして全画面表示",
      qrisBtn: "全画面でQRISを表示",
      modalClose: "閉じる",
      modalBadge: "QRIS 決済",
      modalInfo: "ムハンマド・ダファ・プラタマ · 各種電子マネー / 銀行対応",
      modalDownload: "QRコード画像を保存",
    },
    footer: {
      builtBy: "制作：",
      linktree: "リンク集ページ",
      sub: "インドネシア · 職業高校2年",
    },
    linksPage: {
      backHome: "ポートフォリオへ戻る",
      shareTooltip: "このページを共有",
      copiedToast: "クリップボードにコピーしました！",
      profileDesc: "私立職業高校2年生（会計専攻）· デジタルクリエイター",
      btnWebsite: "メインポートフォリオを訪問 →",
      catWa: "WhatsApp ＆ コミュニティ",
      catSocial: "公式ソーシャルメディア",
      catSupport: "応援 ＆ ドネーション",
      waPersonal: "個人WhatsAppチャット",
      waPersonalSub: "直接メッセージを送る",
      waGroup: "コミュニティグループ",
      waGroupSub: "交流・雑談グループに参加",
      waChannel: "公式アップデートチャンネル",
      waChannelSub: "最新のお知らせをお届け",
      saweriaSub: "Saweriaでクリエイターを支援",
      qrisBtnText: "QRIS決済コードを表示",
      qrisSubText: "電子マネー・各社銀行送金に対応",
    },
  },
  jv: {
    nav: {
      home: "Griya",
      about: "Bab Kula",
      skills: "Keahlian",
      contact: "Kontak",
      support: "Dukungan",
      linktree: "Linktree",
    },
    hero: {
      prefix1: "Halo, Kula",
      text1: "Muhammad Dafa Pratama",
      prefix2: "Wiyosan (Lahir)",
      text2: "28 Agustus 2009",
      tagline: "Murid SMK Swasta Kelas XI jurusan AKL ingkang remen ing babagan administrasi, media sosial, lan teknologi digital.",
      btnContact: "Kirim Pesen",
      btnWa: "WhatsApp",
      btnBio: "Bio / Linktree",
      statusVal: "ONLINE",
      statusLabel: "Status",
      classVal: "XI AKL",
      classLabel: "Kelas",
      schoolVal: "SMK",
      schoolLabel: "Sekolah",
      badgeSchool: "SMK · XI AKL",
    },
    countdown: {
      title: "Itungan Mundur Tanggap Warsa",
      targetPrefix: "28 Agustus ·",
      days: "Dina",
      hours: "Jam",
      mins: "Menit",
      secs: "Detik",
    },
    about: {
      badge: "02. Bab Kula",
      titlePre: "Bab",
      titlePost: "Kula",
      fileName: "profil.json",
      keyName: "asma",
      keySchool: "sekolah",
      valSchool: "SMK Swasta",
      keyGrade: "kelas",
      valGrade: "XI (11)",
      keyMajor: "jurusan",
      valMajor: "Akuntansi lan Keuangan Lembaga (AKL)",
      keyStatus: "kahanan",
      valStatus: "Murid Aktif",
      keyInterest: "kesenengan",
      valInterest1: "Administrasi Dhuwit",
      valInterest2: "Ngatur Medsos",
      valInterest3: "Teknologi Digital",
      tile1Title: "Murid SMK Swasta",
      tile1Desc: "Sinau wonten SMK Swasta Kelas XI jurusan Akuntansi lan Keuangan Lembaga.",
      tile2Title: "Keahlian AKL",
      tile2Desc: "Paham babagan cathetan dhuwit, transaksi, Microsoft Excel, lan Word.",
      tile3Title: "Digital & Medsos",
      tile3Desc: "Aktif ngelola media sosial lan gawe konten ing jagad digital.",
      socialTitle: "Akun Medsos & Komunitas",
    },
    skills: {
      badge: "03. Keahlian",
      titlePre: "Keahlian",
      titlePost: "Kula",
      skillExcel: "Microsoft Excel",
      skillWord: "Microsoft Word",
      skillSocial: "Ngatur Media Sosial",
      waTitle: "Komunitas & Saluran WhatsApp",
      waDesc: "Grup pirembagan lan kabar anyar babagan kegiyatan Dafa",
      joinGroup: "Mlebu Grup WA",
      followChannel: "Melu Saluran WA",
    },
    contact: {
      badge: "04. Kontak",
      titlePre: "Hubungi",
      titlePost: "Kula",
      desc: "Wonten pitakon utawa ajakan rembugan? Kirim pesen langsung wonten bot Telegram kula!",
      formBar: "PESEN_ANYAR.SYS",
      labelName: "Asma Jangkep / Celukan:",
      phName: "Lebokna asma panjenengan...",
      labelContact: "Kontak Wangsulan (WA / Telegram):",
      phContact: "Tuladha: 08123456789 utawa @username",
      labelMsg: "Pesen:",
      phMsg: "Serat pesen panjenengan wonten mriki...",
      sliderIdle: "Geser nengen kagem verifikasi",
      sliderFailed: "! Geser nganti menthok nengen",
      sliderVerified: "✓ Sampun Sah!",
      sliderHint: "Geser nengen →",
      readyToSend: "Sampun Sah — Siap Dikirim!",
      btnSend: "Kirim Pesen Sakmenika →",
      btnSending: "Nglakoni Kirim...",
      successTitle: "Pesen Sampun Kintun!",
      successDesc: "Pesenipun sampun lumebu Telegram bot kula. Kula badhe mangsuli wonten kontak panjenengan.",
      btnSendAnother: "Kirim Pesen Liyane",
    },
    payment: {
      badge: "05. Panyengkuyung",
      titlePre: "Dukung",
      titlePost: "Kula",
      desc: "Menawi badhe maringi panyengkuyung utawa donasi, saged transfer liwat e-wallet utawa QRIS:",
      copyBtn: "Salin",
      copiedBtn: "Kasil Disalin",
      saweriaTitle: "Saweria Donasi",
      saweriaOpen: "Bukak →",
      qrisTitle: "Scan Pembayaran QRIS",
      qrisSub: "Klik kagem mirsani QRIS wutuh",
      qrisBtn: "Tingali QRIS Wutuh",
      modalClose: "Tutup",
      modalBadge: "QRIS PEMBAYARAN",
      modalInfo: "Muhammad Dafa Pratama · Dana / Gopay / OVO / ShopeePay / Bank",
      modalDownload: "Undhuh Gambar QRIS",
    },
    footer: {
      builtBy: "Kadamêl dening",
      linktree: "Kaca Linktree",
      sub: "SMK XI AKL · Indonesia",
    },
    linksPage: {
      backHome: "Kaca Ngarep Portfolio",
      shareTooltip: "Bagekna Kaca Iki",
      copiedToast: "Kasil disalin ing papan klip!",
      profileDesc: "Murid SMK Swasta Kelas XI AKL · Digital & Content Creator",
      btnWebsite: "Dolan menyang Website Portfolio Utama →",
      catWa: "WhatsApp & Komunitas",
      catSocial: "Medsos Resmi",
      catSupport: "Panyengkuyung & Donasi",
      waPersonal: "WhatsApp Chat Pribadi",
      waPersonalSub: "Kirim pesen / rembugan langsung",
      waGroup: "Grup Paguyuban WA",
      waGroupSub: "Melu kumpul lan silaturahmi",
      waChannel: "Saluran Resmi WA",
      waChannelSub: "Kabar lan pengumuman paling anyar",
      saweriaSub: "Menehi apresiasi liwat Saweria",
      qrisBtnText: "Tuduhna QRIS Pembayaran",
      qrisSubText: "Scan nganggo Dana, Gopay, OVO, ShopeePay & Bank",
    },
  },
  su: {
    nav: {
      home: "Tepas",
      about: "Ngeunaan",
      skills: "Kamampuh",
      contact: "Kontak",
      support: "Rojong",
      linktree: "Linktree",
    },
    hero: {
      prefix1: "Sampurasun, Abdi",
      text1: "Muhammad Dafa Pratama",
      prefix2: "Titimangsa Lahir",
      text2: "28 Agustus 2009",
      tagline: "Murid SMK Swasta Kelas XI jurusan AKL anu museur dina widang administrasi, media sosial, sareng téknologi digital.",
      btnContact: "Kirim Pesen",
      btnWa: "WhatsApp",
      btnBio: "Bio / Linktree",
      statusVal: "ONLINE",
      statusLabel: "Status",
      classVal: "XI AKL",
      classLabel: "Kelas",
      schoolVal: "SMK",
      schoolLabel: "Sakola",
      badgeSchool: "SMK · XI AKL",
    },
    countdown: {
      title: "Itungan Mundur Milangkala",
      targetPrefix: "28 Agustus ·",
      days: "Dinten",
      hours: "Jam",
      mins: "Menit",
      secs: "Detik",
    },
    about: {
      badge: "02. Ngeunaan",
      titlePre: "Ngeunaan",
      titlePost: "Abdi",
      fileName: "profil.json",
      keyName: "nami",
      keySchool: "sakola",
      valSchool: "SMK Swasta",
      keyGrade: "kelas",
      valGrade: "XI (11)",
      keyMajor: "jurusan",
      valMajor: "Akuntansi jeung Keuangan Lembaga (AKL)",
      keyStatus: "status",
      valStatus: "Murid Aktip",
      keyInterest: "minat",
      valInterest1: "Administrasi Kauangan",
      valInterest2: "Manajemén Médiasosial",
      valInterest3: "Téknologi Digital",
      tile1Title: "Murid SMK Swasta",
      tile1Desc: "Nuju sakola di SMK Swasta Kelas XI jurusan Akuntansi jeung Keuangan Lembaga.",
      tile2Title: "Kamampuh AKL",
      tile2Desc: "Maham kana pambukuan, administrasi transaksi, Microsoft Excel, sareng Word.",
      tile3Title: "Digital & Médiasosial",
      tile3Desc: "Aktip ngokolakeun média sosial sareng ngadamel kontén dina dunya digital.",
      socialTitle: "Akun Média Sosial & Komunitas",
    },
    skills: {
      badge: "03. Kamampuh",
      titlePre: "Kamampuh",
      titlePost: "Abdi",
      skillExcel: "Microsoft Excel",
      skillWord: "Microsoft Word",
      skillSocial: "Manajemén Médiasosial",
      waTitle: "Komunitas & Saluran WhatsApp",
      waDesc: "Grup sawala sareng warta panganyarna sabudeureun kagiatan Dafa",
      joinGroup: "Lebet Grup WA",
      followChannel: "Tuturkeun Saluran WA",
    },
    contact: {
      badge: "04. Kontak",
      titlePre: "Tepung",
      titlePost: "Abdi",
      desc: "Aya patarosan atanapi hoyong kolaborasi? Kirim pesen langsung ka bot Telegram abdi!",
      formBar: "PESEN_ENAL.SYS",
      labelName: "Nami Lengkep / Landian:",
      phName: "Lebetkeun nami anjeun...",
      labelContact: "Kontak Waleran (No. WA / Telegram):",
      phContact: "Conto: 08123456789 atanapi @username",
      labelMsg: "Pesen:",
      phMsg: "Tulis pesen atanapi peryogi anjeun di dieu...",
      sliderIdle: "Gésér ka katuhu kanggo vérifikasi",
      sliderFailed: "! Gésér dugi ka tungtung katuhu",
      sliderVerified: "✓ Parantos Sah!",
      sliderHint: "Gésér ka katuhu →",
      readyToSend: "Parantos Sah — Siap Dikirim!",
      btnSend: "Kirim Pesen Ayeuna →",
      btnSending: "Nuju Ngirim...",
      successTitle: "Pesen Parantos Kintun!",
      successDesc: "Pesen parantos dugi ka Telegram bot abdi. Abdi baris ngawaler kana kontak anjeun.",
      btnSendAnother: "Kirim Pesen Séjén",
    },
    payment: {
      badge: "05. Rojongan & Donasi",
      titlePre: "Rojong",
      titlePost: "Abdi",
      desc: "Upami hoyong masihan pangrojong atanapi donasi, tiasa ngalangkungan e-wallet atanapi scan QRIS:",
      copyBtn: "Salin",
      copiedBtn: "Kasalim",
      saweriaTitle: "Saweria Donasi",
      saweriaOpen: "Buka →",
      qrisTitle: "Scan Pamayaran QRIS",
      qrisSub: "Klik kanggo ningali QRIS pinuh",
      qrisBtn: "Tingali QRIS Pinuh",
      modalClose: "Tutup",
      modalBadge: "QRIS PAMAYARAN",
      modalInfo: "Muhammad Dafa Pratama · Dana / Gopay / OVO / ShopeePay / Bank",
      modalDownload: "Unduh Gambar QRIS",
    },
    footer: {
      builtBy: "Dijieun ku",
      linktree: "Kaca Linktree",
      sub: "SMK XI AKL · Indonesia",
    },
    linksPage: {
      backHome: "Halaman Utama Portfolio",
      shareTooltip: "Bagikeun Kaca Ieu",
      copiedToast: "Kacutat kana papan klip!",
      profileDesc: "Murid SMK Swasta Kelas XI AKL · Digital Creator & Content Creator",
      btnWebsite: "Buka Website Utama Portfolio →",
      catWa: "WhatsApp & Komunitas",
      catSocial: "Média Sosial Resmi",
      catSupport: "Rojongan & Donasi",
      waPersonal: "WhatsApp Chat Pribadi",
      waPersonalSub: "Kirim pesen / ngawangkong langsung",
      waGroup: "Grup Komunitas WhatsApp",
      waGroupSub: "Gabung kana grup sawala & silaturahmi",
      waChannel: "Saluran Resmi WhatsApp",
      waChannelSub: "Warta sareng bewara panganyarna",
      saweriaSub: "Masihan apresiasi ngalangkungan Saweria",
      qrisBtnText: "Tembongkeun QRIS Pamayaran",
      qrisSubText: "Scan liwat Dana, Gopay, OVO, ShopeePay & Bank",
    },
  },
  zh: {
    nav: {
      home: "主页",
      about: "关于",
      skills: "技能",
      contact: "联系",
      support: "支持",
      linktree: "链接树",
    },
    hero: {
      prefix1: "你好，我是",
      text1: "穆罕默德·达法·普拉塔马",
      prefix2: "出生日期",
      text2: "2009年8月28日",
      tagline: "私立职业高中二年级（会计系）学生，专注财务行政、社交媒体管理与数字技术领域。",
      btnContact: "发送消息",
      btnWa: "WhatsApp",
      btnBio: "个人链接树",
      statusVal: "在线",
      statusLabel: "状态",
      classVal: "高二 会计班",
      classLabel: "年级",
      schoolVal: "职高",
      schoolLabel: "学校",
      badgeSchool: "职高 · 会计系",
    },
    countdown: {
      title: "生日倒计时",
      targetPrefix: "8月28日 ·",
      days: "天",
      hours: "时",
      mins: "分",
      secs: "秒",
    },
    about: {
      badge: "02. 关于我",
      titlePre: "关于",
      titlePost: "达法",
      fileName: "profile.json",
      keyName: "姓名",
      keySchool: "学校",
      valSchool: "私立职业高中",
      keyGrade: "年级",
      valGrade: "高二 (11班)",
      keyMajor: "专业",
      valMajor: "会计与金融机构系 (AKL)",
      keyStatus: "状态",
      valStatus: "在校学生",
      keyInterest: "爱好领域",
      valInterest1: "财务账目管理",
      valInterest2: "社交平台运营",
      valInterest3: "数字技术实践",
      tile1Title: "私立职高学子",
      tile1Desc: "就读于私立职业高中高二年级会计与金融专业。",
      tile2Title: "会计与办公专业",
      tile2Desc: "掌握基础记账、商务单据、微软Excel以及Word软件操作。",
      tile3Title: "数字与社交媒体",
      tile3Desc: "积极运营社交媒体社群与数字内容创作交流。",
      socialTitle: "官方社交媒体与社群",
    },
    skills: {
      badge: "03. 个人技能",
      titlePre: "我的",
      titlePost: "特长",
      skillExcel: "微软 Excel 数据表格",
      skillWord: "微软 Word 文档排版",
      skillSocial: "社交媒体运营管理",
      waTitle: "WhatsApp 官方社区与频道",
      waDesc: "讨论组与关于达法动态的最新资讯通知",
      joinGroup: "加入 WA 交流群",
      followChannel: "关注 WA 频道",
    },
    contact: {
      badge: "04. 留言联系",
      titlePre: "联系",
      titlePost: "我",
      desc: "有疑问或寻求合作？可直接给我绑定的 Telegram 机器人发送消息！",
      formBar: "MESSAGE_FORM.SYS",
      labelName: "您的姓名 / 称呼:",
      phName: "请输入您的姓名...",
      labelContact: "回复联系方式 (电话 / Telegram):",
      phContact: "例如: 08123456789 或 @用户名",
      labelMsg: "留言内容:",
      phMsg: "请在此写下您的留言或合作需求...",
      sliderIdle: "向右滑动以进行人机验证",
      sliderFailed: "! 请完全滑动至最右端",
      sliderVerified: "✓ 验证成功！",
      sliderHint: "向右滑动 →",
      readyToSend: "验证通过 — 可立即发送！",
      btnSend: "立即发送留言 →",
      btnSending: "正在发送中...",
      successTitle: "留言已成功送达！",
      successDesc: "通知已即时推送到我的 Telegram 机器人，我将尽快通过您留下的方式回复。",
      btnSendAnother: "发送其他留言",
    },
    payment: {
      badge: "05. 赞赏与支持",
      titlePre: "支持",
      titlePost: "作者",
      desc: "如果您希望赞助支持，可通过电子钱包或扫描下方 QRIS 码完成打赏：",
      copyBtn: "复制",
      copiedBtn: "已复制",
      saweriaTitle: "Saweria 赞赏平台",
      saweriaOpen: "前往 →",
      qrisTitle: "扫描 QRIS 支付",
      qrisSub: "点击查看高清全屏二维码",
      qrisBtn: "全屏查看 QRIS 码",
      modalClose: "关闭",
      modalBadge: "QRIS 快捷支付",
      modalInfo: "穆罕默德·达法·普拉塔马 · 支持各大电子钱包及银行扫码",
      modalDownload: "下载保存 QRIS 码",
    },
    footer: {
      builtBy: "开发制作：",
      linktree: "个人链接树页面",
      sub: "印尼 · 职业高中二年级",
    },
    linksPage: {
      backHome: "返回个人主页",
      shareTooltip: "分享当前页面",
      copiedToast: "链接已复制到剪贴板！",
      profileDesc: "私立职业高中会计系高二生 · 数字化创作者",
      btnWebsite: "访问个人作品集主站 →",
      catWa: "WhatsApp 与社群",
      catSocial: "官方社交媒体",
      catSupport: "赞赏与支持",
      waPersonal: "个人 WhatsApp 聊天",
      waPersonalSub: "直接发送私信聊天",
      waGroup: "WhatsApp 社群交流群",
      waGroupSub: "加入讨论与结交新朋友",
      waChannel: "官方 WhatsApp 动态频道",
      waChannelSub: "获取最新通知与动态发布",
      saweriaSub: "通过 Saweria 平台赞赏打赏",
      qrisBtnText: "显示 QRIS 支付二维码",
      qrisSubText: "支持 Dana, Gopay, OVO, ShopeePay 及各大网银扫码",
    },
  },
  ar: {
    nav: {
      home: "الرئيسية",
      about: "عنّي",
      skills: "المهارات",
      contact: "اتصل بي",
      support: "الدعم",
      linktree: "الروابط",
    },
    hero: {
      prefix1: "مرحباً، أنا",
      text1: "محمد دافا براتاما",
      prefix2: "تاريخ الميلاد",
      text2: "28 أغسطس 2009",
      tagline: "طالب بالصف الحادي عشر في مدرسة مهنية خاصة بقسم المحاسبة، أركز على الإدارة ووسائل التواصل الاجتماعي والتقنية الرقمية.",
      btnContact: "إرسال رسالة",
      btnWa: "واتساب",
      btnBio: "شجرة الروابط",
      statusVal: "متصل الآن",
      statusLabel: "الحالة",
      classVal: "الصف 11 محاسبة",
      classLabel: "الصف",
      schoolVal: "ثانوية مهنية",
      schoolLabel: "المدرسة",
      badgeSchool: "مدرسة مهنية · الصف 11",
    },
    countdown: {
      title: "العد التنازلي ليوم الميلاد",
      targetPrefix: "28 أغسطس ·",
      days: "أيام",
      hours: "ساعات",
      mins: "دقائق",
      secs: "ثوانٍ",
    },
    about: {
      badge: "02. نبذة عني",
      titlePre: "نبذة",
      titlePost: "عنّي",
      fileName: "profile.json",
      keyName: "الاسم",
      keySchool: "المدرسة",
      valSchool: "مدرسة مهنية خاصة",
      keyGrade: "الصف",
      valGrade: "الحادي عشر (11)",
      keyMajor: "التخصص",
      valMajor: "المحاسبة والمالية المؤسسية (AKL)",
      keyStatus: "الحالة",
      valStatus: "طالب نشط",
      keyInterest: "الاهتمامات",
      valInterest1: "الإدارة المالية",
      valInterest2: "إدارة وسائل التواصل",
      valInterest3: "التقنية الرقمية",
      tile1Title: "طالب ثانوية مهنية خاصة",
      tile1Desc: "أدرس بالصف الحادي عشر متخصصاً في مجال المحاسبة والمالية المؤسسية.",
      tile2Title: "مهارات المحاسبة",
      tile2Desc: "إتقان مبادئ مسك الدفاتر والمعاملات المكتبية وبرامج إكسل ووورد.",
      tile3Title: "الإعلام الرقمي",
      tile3Desc: "إدارة المجتمعات الرقمية وصناعة المحتوى عبر المنصات المختلفة.",
      socialTitle: "حسابات التواصل والمجتمع",
    },
    skills: {
      badge: "03. المهارات",
      titlePre: "مهاراتي",
      titlePost: "الشخصية",
      skillExcel: "مايكروسوفت إكسل",
      skillWord: "مايكروسوفت وورد",
      skillSocial: "إدارة وسائل التواصل",
      waTitle: "مجتمع وقناة واتساب",
      waDesc: "مجموعة للنقاشات والتحديثات حول نشاطات دافا",
      joinGroup: "انضم لمجموعة واتساب",
      followChannel: "متابعة قناة واتساب",
    },
    contact: {
      badge: "04. اتصل بي",
      titlePre: "تواصل",
      titlePost: "معي",
      desc: "لديك استفسار أو ترغب بالتعاون؟ أرسل رسالة مباشرة إلى بوت تيليجرام الخاص بي!",
      formBar: "MESSAGE_FORM.SYS",
      labelName: "الاسم الكامل / اللقب:",
      phName: "اكتب اسمك هنا...",
      labelContact: "معلومات التواصل للرد (واتساب / تيليجرام):",
      phContact: "مثال: 08123456789 أو @username",
      labelMsg: "الرسالة:",
      phMsg: "اكتب رسالتك أو استفسارك هنا...",
      sliderIdle: "مرر إلى اليمين للتحقق",
      sliderFailed: "! مرر حتى النهاية إلى اليمين",
      sliderVerified: "✓ تم التحقق بنجاح!",
      sliderHint: "مرر لليمين →",
      readyToSend: "تم التحقق — جاهز للإرسال!",
      btnSend: "إرسال الرسالة الآن →",
      btnSending: "جارٍ الإرسال...",
      successTitle: "تم إرسال الرسالة بنجاح!",
      successDesc: "وصل الإشعار مباشرة إلى بوت تيليجرام. سأتواصل معك عبر الوسيلة المحددة.",
      btnSendAnother: "إرسال رسالة أخرى",
    },
    payment: {
      badge: "05. الدعم والمساهمة",
      titlePre: "دعم",
      titlePost: "أعمالي",
      desc: "يمكن تقديم الدعم أو المساهمة عبر المحافظ الإلكترونية أو مسح رمز QRIS:",
      copyBtn: "نسخ",
      copiedBtn: "تم النسخ",
      saweriaTitle: "دعم عبر منصة Saweria",
      saweriaOpen: "فتح →",
      qrisTitle: "مسح رمز الدفع QRIS",
      qrisSub: "اضغط لعرض الرمز بحجم الشاشة",
      qrisBtn: "عرض رمز QRIS كاملاً",
      modalClose: "إغلاق",
      modalBadge: "دفع QRIS",
      modalInfo: "محمد دافا براتاما · متاح عبر المحافظ والتطبيقات البنكية",
      modalDownload: "تحميل صورة QRIS",
    },
    footer: {
      builtBy: "تم التطوير بواسطة",
      linktree: "صفحة شجرة الروابط",
      sub: "إندونيسيا · الصف 11 محاسبة",
    },
    linksPage: {
      backHome: "العودة للموقع الشخصي",
      shareTooltip: "مشاركة الصفحة",
      copiedToast: "تم نسخ الرابط إلى الحافظة!",
      profileDesc: "طالب ثانوية مهنية محاسبة · صانع محتوى رقمي",
      btnWebsite: "زيارة الموقع الرئيسي للملف التعريفي →",
      catWa: "واتساب والمجتمع",
      catSocial: "الحسابات الرسمية",
      catSupport: "الدعم والمساهمة",
      waPersonal: "محادثة واتساب شخصية",
      waPersonalSub: "إرسال رسالة مباشرة / محادثة",
      waGroup: "مجموعة مجتمع واتساب",
      waGroupSub: "الانضمام للمناقشات والتعارف",
      waChannel: "قناة واتساب الرسمية",
      waChannelSub: "آخر الأخبار والإعلانات الهامة",
      saweriaSub: "تقديم الدعم عبر Saweria",
      qrisBtnText: "عرض رمز QRIS للدفع",
      qrisSubText: "مسح عبر Dana و Gopay والمحافظ البنكية",
    },
  },
  fr: {
    nav: {
      home: "Accueil",
      about: "À propos",
      skills: "Compétences",
      contact: "Contact",
      support: "Soutien",
      linktree: "Linktree",
    },
    hero: {
      prefix1: "Salut, je suis",
      text1: "Muhammad Dafa Pratama",
      prefix2: "Date de naissance",
      text2: "28 août 2009",
      tagline: "Élève de 1ère en lycée professionnel privé (filière Comptabilité), passionné d'administration, réseaux sociaux et technologies numériques.",
      btnContact: "Envoyer un message",
      btnWa: "WhatsApp",
      btnBio: "Bio / Linktree",
      statusVal: "EN LIGNE",
      statusLabel: "Statut",
      classVal: "1ère AKL",
      classLabel: "Classe",
      schoolVal: "Lycée Pro",
      schoolLabel: "École",
      badgeSchool: "Lycée Pro · 1ère AKL",
    },
    countdown: {
      title: "Compte à rebours anniversaire",
      targetPrefix: "28 août ·",
      days: "Jours",
      hours: "Heures",
      mins: "Minutes",
      secs: "Secondes",
    },
    about: {
      badge: "02. À propos",
      titlePre: "À propos de",
      titlePost: "Moi",
      fileName: "profil.json",
      keyName: "nom",
      keySchool: "école",
      valSchool: "Lycée Professionnel Privé",
      keyGrade: "classe",
      valGrade: "1ère (11e année)",
      keyMajor: "filière",
      valMajor: "Comptabilité et Finance Institutionnelle (AKL)",
      keyStatus: "statut",
      valStatus: "Élève actif",
      keyInterest: "intérêts",
      valInterest1: "Gestion Financière",
      valInterest2: "Gestion des Médias Sociaux",
      valInterest3: "Technologies Numériques",
      tile1Title: "Élève en Lycée Pro Privé",
      tile1Desc: "Actuellement en classe de 1ère filière Comptabilité et Finance Institutionnelle.",
      tile2Title: "Compétences Comptables",
      tile2Desc: "Maîtrise de la tenue de livres, des transactions administratives, de Microsoft Excel et Word.",
      tile3Title: "Digital & Médias Sociaux",
      tile3Desc: "Gestion active de communautés en ligne et création de contenus numériques.",
      socialTitle: "Réseaux Sociaux & Communauté",
    },
    skills: {
      badge: "03. Compétences",
      titlePre: "Mes",
      titlePost: "Atouts",
      skillExcel: "Microsoft Excel",
      skillWord: "Microsoft Word",
      skillSocial: "Gestion des Réseaux Sociaux",
      waTitle: "Communauté & Canal WhatsApp",
      waDesc: "Groupe d'échange et actualités sur les activités de Dafa",
      joinGroup: "Rejoindre le groupe WA",
      followChannel: "Suivre le canal WA",
    },
    contact: {
      badge: "04. Contact",
      titlePre: "Contactez-",
      titlePost: "Moi",
      desc: "Une question ou envie de collaborer ? Envoyez directement un message à mon bot Telegram !",
      formBar: "MESSAGE_FORM.SYS",
      labelName: "Nom complet / Pseudo :",
      phName: "Entrez votre nom...",
      labelContact: "Contact de réponse (N° WhatsApp / Telegram) :",
      phContact: "Ex : 08123456789 ou @pseudo",
      labelMsg: "Message :",
      phMsg: "Écrivez votre message ou demande ici...",
      sliderIdle: "Glissez vers la droite pour vérifier",
      sliderFailed: "! Glissez jusqu'au bout à droite",
      sliderVerified: "✓ Vérifié !",
      sliderHint: "Glisser vers la droite →",
      readyToSend: "Vérifié — Prêt à l'envoi !",
      btnSend: "Envoyer le message →",
      btnSending: "Envoi en cours...",
      successTitle: "Message envoyé avec succès !",
      successDesc: "La notification est parvenue à mon bot Telegram. Je vous répondrai au contact indiqué.",
      btnSendAnother: "Envoyer un autre message",
    },
    payment: {
      badge: "05. Soutien & Don",
      titlePre: "Soutenir",
      titlePost: "Dafa",
      desc: "Si vous souhaitez exprimer votre soutien ou faire un don, via e-wallet ou par QRIS ci-dessous :",
      copyBtn: "Copier",
      copiedBtn: "Copié",
      saweriaTitle: "Don via Saweria",
      saweriaOpen: "Ouvrir →",
      qrisTitle: "Scanner le QRIS",
      qrisSub: "Cliquez pour afficher en plein écran",
      qrisBtn: "Voir le QRIS plein écran",
      modalClose: "Fermer",
      modalBadge: "PAIEMENT QRIS",
      modalInfo: "Muhammad Dafa Pratama · Compatible Dana / Gopay / OVO / Banques",
      modalDownload: "Télécharger le QRIS",
    },
    footer: {
      builtBy: "Créé par",
      linktree: "Page Linktree",
      sub: "Lycée Pro 1ère AKL · Indonésie",
    },
    linksPage: {
      backHome: "Site Portfolio",
      shareTooltip: "Partager cette page",
      copiedToast: "Copié dans le presse-papier !",
      profileDesc: "Élève de 1ère en Lycée Pro · Créateur de contenu digital",
      btnWebsite: "Visiter le site portfolio principal →",
      catWa: "WhatsApp & Communauté",
      catSocial: "Réseaux Sociaux Officiels",
      catSupport: "Soutien & Don",
      waPersonal: "Chat WhatsApp Personnel",
      waPersonalSub: "Envoyer un message direct / échanger",
      waGroup: "Groupe Communautaire WhatsApp",
      waGroupSub: "Rejoindre le groupe d'échange & entraide",
      waChannel: "Canal Officiel WhatsApp",
      waChannelSub: "Annonces et dernières actualités",
      saweriaSub: "Faire un don via Saweria",
      qrisBtnText: "Afficher le QRIS de paiement",
      qrisSubText: "Scan via Dana, Gopay, OVO, ShopeePay & banques",
    },
  },
};

export type TranslationsType = typeof translations.id;

interface LanguageContextType {
  lang: LanguageCode;
  setLang: (lang: LanguageCode) => void;
  t: TranslationsType;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "id",
  setLang: () => {},
  t: translations.id,
  languages: LANGUAGES,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LanguageCode>("id");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    try {
      const savedLang = localStorage.getItem("daps_portfolio_lang") as LanguageCode | null;
      if (savedLang && LANGUAGES.some((l) => l.code === savedLang)) {
        setLangState(savedLang);
      }
    } catch {}
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    try {
      localStorage.setItem("daps_portfolio_lang", lang);
      document.documentElement.lang = lang;
      if (lang === "ar") {
        document.documentElement.setAttribute("dir", "rtl");
      } else {
        document.documentElement.setAttribute("dir", "ltr");
      }
    } catch {}
  }, [lang, mounted]);

  const setLang = (newLang: LanguageCode) => {
    setLangState(newLang);
  };

  const currentT = translations[lang] || translations.id;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: currentT, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

// ─── Language Switcher Button Component ──────────────────────────────────────
export function LanguageSwitcher() {
  const { lang, setLang, languages } = useLanguage();
  const [open, setOpen] = useState(false);

  const currentOption = languages.find((l) => l.code === lang) || languages[0];

  return (
    <div className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-1.5 px-2.5 sm:px-3 py-1.5 border-2 border-black bg-white text-black font-mono text-xs font-bold shadow-[2px_2px_0px_#000] hover:shadow-[3px_3px_0px_#000] hover:-translate-x-0.5 hover:-translate-y-0.5 active:translate-x-0.5 active:translate-y-0.5 active:shadow-none transition-all"
        title="Ganti Bahasa / Change Language"
      >
        <GlobeIcon className="w-3.5 h-3.5 text-black" />
        <span className="font-mono text-xs font-black">{currentOption.badge}</span>
      </button>

      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
          <div className="absolute right-0 mt-2 w-52 border-3 border-black bg-white p-2.5 shadow-[5px_5px_0px_#000] z-50 animate-fade-up text-black font-mono">
            <div className="flex items-center justify-between pb-1.5 mb-2 border-b-2 border-black">
              <span className="text-[11px] font-black uppercase tracking-wider">Pilih Bahasa</span>
              <span className="text-[10px] bg-black text-white px-1 font-bold">i18n</span>
            </div>

            <div className="flex flex-col gap-1 max-h-60 overflow-y-auto pr-0.5">
              {languages.map((l) => {
                const isSelected = l.code === lang;
                return (
                  <button
                    key={l.code}
                    onClick={() => {
                      setLang(l.code);
                      setOpen(false);
                    }}
                    className={`flex items-center justify-between px-2 py-1.5 border-2 border-black text-xs font-bold transition-all ${
                      isSelected
                        ? "bg-[#FFE135] text-black shadow-[2px_2px_0px_#000]"
                        : "bg-[#f4f4f5] text-black hover:bg-gray-200"
                    }`}
                  >
                    <div className="flex items-center gap-2">
                      <span className="text-sm">{l.flag}</span>
                      <div className="text-left">
                        <p className="leading-none text-xs font-black">{l.name}</p>
                        <p className="text-[10px] text-gray-600 font-normal leading-tight mt-0.5">
                          {l.nativeName}
                        </p>
                      </div>
                    </div>
                    {isSelected && <CheckIcon className="w-3.5 h-3.5 text-black stroke-[3]" />}
                  </button>
                );
              })}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
